'use client';

import { useEffect, useState } from 'react';
import InvestorSidebar from '@/components/InvestorSidebar';
import { Icon } from '@iconify/react';

type Application = { id: number; status: string; documentPath: string; reviewNote: string | null };
export default function KycPage() { const [idFile, setIdFile] = useState<File | null>(null); const [addressFile, setAddressFile] = useState<File | null>(null); const [application, setApplication] = useState<Application | null>(null); const [message, setMessage] = useState(''); const [loading, setLoading] = useState(true); async function load() { const response = await fetch('/api/kyc', { cache: 'no-store' }); if (response.ok) { const rows = await response.json(); setApplication(rows[0] ?? null); } setLoading(false); } useEffect(() => { void load(); }, []); async function submit(event: React.FormEvent) { event.preventDefault(); if (!idFile || !addressFile) return; setMessage('Uploading documents…'); const paths: string[] = []; for (const file of [idFile, addressFile]) { const form = new FormData(); form.append('file', file); form.append('purpose', 'kyc'); const upload = await fetch('/api/uploads', { method: 'POST', body: form }); const data = await upload.json().catch(() => ({})); if (!upload.ok) { setMessage(data.error ?? 'Document upload failed.'); return; } paths.push(data.path); } const response = await fetch('/api/kyc', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ documentPath: paths.join('|') }) }); const data = await response.json().catch(() => ({})); setMessage(response.ok ? 'Documents submitted for review.' : data.error ?? 'KYC submission failed.'); await load(); }
return <div className="min-h-screen bg-[#0A0F11] text-[#F3F7F4] flex flex-col md:flex-row font-sans"><InvestorSidebar /><main className="flex-1 p-4 sm:p-8 space-y-8 overflow-y-auto pb-24 md:pb-8"><div className="border-b border-[#263437] pb-6"><h1 className="text-2xl font-normal">Identity Verification (KYC)</h1><p className="mt-1 text-xs text-[#93A09A]">Upload your identity documents for manual review.</p></div><div className="max-w-2xl rounded-2xl border border-[#263437] bg-[#141C1F] p-6 sm:p-8 space-y-6">{message && <div role="status" className="rounded-xl border border-[#22C55E]/40 bg-[#22C55E]/10 p-4 text-xs text-[#86EFAC]">{message}</div>}<div className="flex items-center justify-between rounded-xl border border-[#263437] bg-[#0A0F11] p-4 text-xs"><span className="text-[#93A09A]">Verification status</span><span className="rounded-full bg-amber-500/20 px-3 py-1 font-mono text-amber-300">{loading ? 'LOADING' : (application?.status ?? 'NOT SUBMITTED').toUpperCase()}</span></div>{application?.status === 'approved' ? <div className="py-8 text-center"><Icon icon="solar:shield-check-bold" className="mx-auto h-12 w-12 text-[#22C55E]" /><h2 className="mt-3 text-lg">Identity verified</h2><p className="mt-2 text-xs text-[#93A09A]">Your account is approved for verified investor workflows.</p></div> : <form onSubmit={submit} className="space-y-5"><label className="block text-xs text-[#93A09A]">Government ID<input required type="file" accept="image/jpeg,image/png,image/webp" onChange={event => setIdFile(event.target.files?.[0] ?? null)} className="mt-2 w-full text-xs" /></label><label className="block text-xs text-[#93A09A]">Proof of address<input required type="file" accept="image/jpeg,image/png,image/webp" onChange={event => setAddressFile(event.target.files?.[0] ?? null)} className="mt-2 w-full text-xs" /></label><button disabled={!idFile || !addressFile} className="w-full rounded-full bg-[#22C55E] py-3.5 text-xs font-semibold text-[#07110B] disabled:opacity-40">Submit KYC verification</button></form>}</div></main></div>; }
