'use client';

import { useEffect, useState } from 'react';
import AdminSidebar from '@/components/AdminSidebar';

type Withdrawal = { id: number; investorId: string; amountCents: number; destinationType: string; destination: string; destinationDetails: string | null; status: string; createdAt: string };

export default function AdminReferralPayoutsPage() {
  const [rows, setRows] = useState<Withdrawal[]>([]);
  const [message, setMessage] = useState('');
  const [note, setNote] = useState('');
  async function load() { const response = await fetch('/api/admin/referrals/withdrawals', { cache: 'no-store' }); if (response.ok) setRows(await response.json()); else setMessage('Unable to load the referral payout queue.'); }
  useEffect(() => { void load(); }, []);
  async function settle(withdrawalId: number, action: 'approve' | 'reject') { const response = await fetch('/api/admin/referrals/withdrawals', { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ withdrawalId, action, reviewNote: note }) }); const data = await response.json().catch(() => ({})); setMessage(response.ok ? `Referral withdrawal ${action}d.` : data.error ?? 'Settlement failed.'); if (response.ok) { setNote(''); await load(); } }
  return <div className="min-h-screen bg-[#10161A] text-[#F2F6F3] flex flex-col md:flex-row font-sans"><AdminSidebar /><main className="flex-1 p-4 sm:p-8 space-y-8 overflow-y-auto pb-24 md:pb-8"><div className="border-b border-[#263139] pb-6"><h1 className="text-2xl font-normal">Referral Payout Review</h1><p className="mt-1 text-xs text-[#93A09A]">Approve or reject held referral balances after reviewing the requested bank or crypto destination.</p></div>{message && <div role="status" className="rounded-xl border border-[#F4B860]/40 bg-[#F4B860]/10 p-4 text-xs text-[#F7D99D]">{message}</div>}<label className="block max-w-2xl text-xs text-[#93A09A]">Review note applied to the next action<textarea value={note} onChange={event => setNote(event.target.value)} rows={2} className="mt-2 w-full rounded-xl border border-[#263139] bg-[#151E23] p-3 text-sm text-white" /></label><section className="space-y-3">{rows.length === 0 ? <div className="rounded-2xl border border-dashed border-[#263139] p-12 text-center text-sm text-[#93A09A]">No referral payout requests are currently recorded.</div> : rows.map(row => <article key={row.id} className="rounded-2xl border border-[#263139] bg-[#151E23] p-5"><div className="flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between"><div><p className="font-semibold">${(row.amountCents / 100).toLocaleString(undefined, { minimumFractionDigits: 2 })} · {row.destinationType.toUpperCase()}</p><p className="mt-1 text-xs text-[#93A09A]">Investor {row.investorId} · {row.status}</p><p className="mt-2 break-all text-xs text-[#C8D3CC]">{row.destination}</p>{row.destinationDetails && <p className="mt-1 text-xs text-[#93A09A]">{row.destinationDetails}</p>}</div>{row.status === 'pending' && <div className="flex gap-2"><button onClick={() => settle(row.id, 'approve')} className="rounded-full bg-[#22C55E] px-4 py-2 text-xs font-semibold text-[#07110B]">Approve</button><button onClick={() => settle(row.id, 'reject')} className="rounded-full border border-rose-400/40 px-4 py-2 text-xs font-semibold text-rose-300">Reject</button></div>}</div></article>)}</section></main></div>;
}
