import { index, integer, pgTable, primaryKey, serial, text, timestamp, uniqueIndex, varchar } from "drizzle-orm/pg-core";

export const users = pgTable("users", {
  id: varchar("id", { length: 191 }).primaryKey(),
  name: varchar("name", { length: 191 }),
  email: varchar("email", { length: 191 }).unique(),
  emailVerified: timestamp("emailVerified", { withTimezone: true }),
  image: text("image"),
  phone: varchar("phone", { length: 32 }),
  role: varchar("role", { length: 24 }).default("investor").notNull(),
  createdAt: timestamp("createdAt", { withTimezone: true }).defaultNow().notNull(),
});

export const accounts = pgTable("accounts", {
  userId: varchar("userId", { length: 191 }).notNull(),
  type: varchar("type", { length: 32 }).notNull(),
  provider: varchar("provider", { length: 191 }).notNull(),
  providerAccountId: varchar("providerAccountId", { length: 191 }).notNull(),
  refresh_token: text("refresh_token"), access_token: text("access_token"), expires_at: integer("expires_at"),
  token_type: varchar("token_type", { length: 64 }), scope: varchar("scope", { length: 255 }), id_token: text("id_token"), session_state: varchar("session_state", { length: 255 }),
}, table => ({ pk: primaryKey({ columns: [table.provider, table.providerAccountId] }), userIndex: index("accounts_user_idx").on(table.userId) }));

export const sessions = pgTable("sessions", { sessionToken: varchar("sessionToken", { length: 255 }).primaryKey(), userId: varchar("userId", { length: 191 }).notNull(), expires: timestamp("expires", { withTimezone: true }).notNull() }, table => ({ userIndex: index("sessions_user_idx").on(table.userId) }));
export const verificationTokens = pgTable("verificationTokens", { identifier: varchar("identifier", { length: 191 }).notNull(), token: varchar("token", { length: 255 }).notNull(), expires: timestamp("expires", { withTimezone: true }).notNull() }, table => ({ pk: primaryKey({ columns: [table.identifier, table.token] }) }));

export const deposits = pgTable("deposits", { id: varchar("id", { length: 191 }).primaryKey(), investorId: varchar("investorId", { length: 191 }).notNull(), amountCents: integer("amountCents").notNull(), method: varchar("method", { length: 16 }).notNull(), proofPath: text("proofPath"), planId: integer("planId"), status: varchar("status", { length: 24 }).default("pending").notNull(), reviewedBy: varchar("reviewedBy", { length: 191 }), reviewNote: text("reviewNote"), createdAt: timestamp("createdAt", { withTimezone: true }).defaultNow().notNull(), updatedAt: timestamp("updatedAt", { withTimezone: true }).defaultNow().notNull() }, table => ({ investorIndex: index("deposits_investor_idx").on(table.investorId), statusIndex: index("deposits_status_idx").on(table.status) }));

export const depositInstructions = pgTable("depositInstructions", { id: serial("id").primaryKey(), method: varchar("method", { length: 16 }).notNull(), label: varchar("label", { length: 120 }).notNull(), details: text("details").notNull(), qrPath: text("qrPath"), active: integer("active").default(1).notNull(), updatedBy: varchar("updatedBy", { length: 191 }).notNull(), updatedAt: timestamp("updatedAt", { withTimezone: true }).defaultNow().notNull() }, table => ({ methodUnique: uniqueIndex("deposit_instructions_method_unique").on(table.method) }));
export const kycApplications = pgTable("kycApplications", { id: serial("id").primaryKey(), investorId: varchar("investorId", { length: 191 }).notNull(), documentPath: text("documentPath").notNull(), status: varchar("status", { length: 24 }).default("pending").notNull(), reviewedBy: varchar("reviewedBy", { length: 191 }), reviewNote: text("reviewNote"), createdAt: timestamp("createdAt", { withTimezone: true }).defaultNow().notNull(), updatedAt: timestamp("updatedAt", { withTimezone: true }).defaultNow().notNull() }, table => ({ investorIndex: index("kyc_applications_investor_idx").on(table.investorId), statusIndex: index("kyc_applications_status_idx").on(table.status) }));
export const referralLinks = pgTable("referralLinks", { id: serial("id").primaryKey(), ownerId: varchar("ownerId", { length: 191 }).notNull(), code: varchar("code", { length: 64 }).notNull(), createdAt: timestamp("createdAt", { withTimezone: true }).defaultNow().notNull() }, table => ({ codeUnique: uniqueIndex("referral_links_code_unique").on(table.code), ownerIndex: index("referral_links_owner_idx").on(table.ownerId) }));
export const referralAttributions = pgTable("referralAttributions", { id: serial("id").primaryKey(), referrerId: varchar("referrerId", { length: 191 }).notNull(), referredInvestorId: varchar("referredInvestorId", { length: 191 }).notNull(), linkId: integer("linkId").notNull(), status: varchar("status", { length: 24 }).default("active").notNull(), attributedAt: timestamp("attributedAt", { withTimezone: true }).defaultNow().notNull() }, table => ({ referredUnique: uniqueIndex("referral_attributions_referred_unique").on(table.referredInvestorId), referrerIndex: index("referral_attributions_referrer_idx").on(table.referrerId) }));
export const referralRewards = pgTable("referralRewards", { id: serial("id").primaryKey(), attributionId: integer("attributionId").notNull(), referrerId: varchar("referrerId", { length: 191 }).notNull(), referredInvestorId: varchar("referredInvestorId", { length: 191 }).notNull(), qualifyingDepositId: varchar("qualifyingDepositId", { length: 191 }).notNull(), idempotencyKey: varchar("idempotencyKey", { length: 191 }).notNull(), qualifyingAmountCents: integer("qualifyingAmountCents").notNull(), rewardAmountCents: integer("rewardAmountCents").notNull(), status: varchar("status", { length: 24 }).default("available").notNull(), createdAt: timestamp("createdAt", { withTimezone: true }).defaultNow().notNull() }, table => ({ keyUnique: uniqueIndex("referral_rewards_key_unique").on(table.idempotencyKey), referrerIndex: index("referral_rewards_referrer_idx").on(table.referrerId) }));
export const referralWithdrawals = pgTable("referralWithdrawals", { id: serial("id").primaryKey(), investorId: varchar("investorId", { length: 191 }).notNull(), amountCents: integer("amountCents").notNull(), destinationType: varchar("destinationType", { length: 16 }).notNull(), destination: varchar("destination", { length: 255 }).notNull(), destinationDetails: text("destinationDetails"), status: varchar("status", { length: 24 }).default("pending").notNull(), reviewedBy: varchar("reviewedBy", { length: 191 }), reviewNote: text("reviewNote"), createdAt: timestamp("createdAt", { withTimezone: true }).defaultNow().notNull(), updatedAt: timestamp("updatedAt", { withTimezone: true }).defaultNow().notNull() }, table => ({ investorIndex: index("referral_withdrawals_investor_idx").on(table.investorId) }));

export const plans = pgTable("plans", { id: serial("id").primaryKey(), name: varchar("name", { length: 32 }).notNull(), minimumDepositCents: integer("minimumDepositCents").notNull(), maximumDepositCents: integer("maximumDepositCents"), minRoiBps: integer("minRoiBps").notNull(), maxRoiBps: integer("maxRoiBps").notNull(), active: integer("active").default(1).notNull() });
export const investorAccounts = pgTable("investorAccounts", { id: varchar("id", { length: 191 }).primaryKey(), investorId: varchar("investorId", { length: 191 }).notNull(), planId: integer("planId").notNull(), principalCents: integer("principalCents").default(0).notNull(), balanceCents: integer("balanceCents").default(0).notNull(), status: varchar("status", { length: 24 }).default("active").notNull(), updatedAt: timestamp("updatedAt", { withTimezone: true }).defaultNow().notNull() }, table => ({ investorUnique: uniqueIndex("investor_accounts_investor_unique").on(table.investorId) }));
export const traders = pgTable("traders", { id: varchar("id", { length: 191 }).primaryKey(), name: varchar("name", { length: 191 }).notNull(), imageUrl: text("imageUrl"), imagePath: varchar("imagePath", { length: 255 }), specialty: varchar("specialty", { length: 100 }).notNull(), winRateBps: integer("winRateBps").default(0).notNull(), thirtyDayReturnBps: integer("thirtyDayReturnBps").default(0).notNull(), riskLevel: integer("riskLevel").default(1).notNull(), bio: text("bio"), active: integer("active").default(1).notNull(), createdAt: timestamp("createdAt", { withTimezone: true }).defaultNow().notNull() });
export const roiEntries = pgTable("roiEntries", { id: serial("id").primaryKey(), investorId: varchar("investorId", { length: 191 }).notNull(), planId: integer("planId").notNull(), percentageBps: integer("percentageBps").notNull(), profitCents: integer("profitCents").notNull(), marketNote: text("marketNote").notNull(), publishedBy: varchar("publishedBy", { length: 191 }).notNull(), entryDate: timestamp("entryDate", { withTimezone: true }).defaultNow().notNull(), createdAt: timestamp("createdAt", { withTimezone: true }).defaultNow().notNull() }, table => ({ investorDateUnique: uniqueIndex("roi_entries_investor_date_unique").on(table.investorId, table.entryDate), investorIndex: index("roi_entries_investor_idx").on(table.investorId) }));
export const portfolioLedger = pgTable("portfolioLedger", { id: serial("id").primaryKey(), investorId: varchar("investorId", { length: 191 }).notNull(), type: varchar("type", { length: 32 }).notNull(), amountCents: integer("amountCents").notNull(), referenceId: varchar("referenceId", { length: 191 }), description: text("description"), createdAt: timestamp("createdAt", { withTimezone: true }).defaultNow().notNull() }, table => ({ investorIndex: index("portfolio_ledger_investor_idx").on(table.investorId), referenceUnique: uniqueIndex("portfolio_ledger_reference_unique").on(table.type, table.referenceId) }));
export const investorWithdrawals = pgTable("investorWithdrawals", { id: serial("id").primaryKey(), investorId: varchar("investorId", { length: 191 }).notNull(), amountCents: integer("amountCents").notNull(), destinationType: varchar("destinationType", { length: 16 }).notNull(), destination: varchar("destination", { length: 255 }).notNull(), status: varchar("status", { length: 24 }).default("pending").notNull(), reviewedBy: varchar("reviewedBy", { length: 191 }), reviewNote: text("reviewNote"), createdAt: timestamp("createdAt", { withTimezone: true }).defaultNow().notNull(), updatedAt: timestamp("updatedAt", { withTimezone: true }).defaultNow().notNull() }, table => ({ investorIndex: index("investor_withdrawals_investor_idx").on(table.investorId) }));

export const portfolioHoldings = pgTable("portfolioHoldings", { id: serial("id").primaryKey(), investorId: varchar("investorId", { length: 191 }).notNull(), assetSymbol: varchar("assetSymbol", { length: 16 }).notNull(), assetName: varchar("assetName", { length: 100 }).notNull(), quantity: varchar("quantity", { length: 64 }).default("0").notNull(), costBasisCents: integer("costBasisCents").default(0).notNull(), currentPriceCents: integer("currentPriceCents").default(0).notNull(), createdAt: timestamp("createdAt", { withTimezone: true }).defaultNow().notNull(), updatedAt: timestamp("updatedAt", { withTimezone: true }).defaultNow().notNull() }, table => ({ investorIndex: index("portfolio_holdings_investor_idx").on(table.investorId), symbolIndex: index("portfolio_holdings_symbol_idx").on(table.assetSymbol) }));

export const copyAllocations = pgTable("copyAllocations", { id: serial("id").primaryKey(), investorId: varchar("investorId", { length: 191 }).notNull(), traderId: varchar("traderId", { length: 191 }).notNull(), allocationCents: integer("allocationCents").default(0).notNull(), status: varchar("status", { length: 24 }).default("active").notNull(), createdAt: timestamp("createdAt", { withTimezone: true }).defaultNow().notNull(), updatedAt: timestamp("updatedAt", { withTimezone: true }).defaultNow().notNull() }, table => ({ investorIndex: index("copy_allocations_investor_idx").on(table.investorId), traderIndex: index("copy_allocations_trader_idx").on(table.traderId), investorTraderUnique: uniqueIndex("copy_allocations_investor_trader_unique").on(table.investorId, table.traderId) }));

export const notifications = pgTable("notifications", { id: serial("id").primaryKey(), userId: varchar("userId", { length: 191 }).notNull(), type: varchar("type", { length: 64 }).notNull(), title: varchar("title", { length: 160 }).notNull(), body: text("body").notNull(), relatedRewardId: integer("relatedRewardId"), isRead: integer("isRead").default(0).notNull(), createdAt: timestamp("createdAt", { withTimezone: true }).defaultNow().notNull() }, table => ({ userIndex: index("notifications_user_idx").on(table.userId) }));

export const swapTransactions = pgTable("swapTransactions", { id: serial("id").primaryKey(), investorId: varchar("investorId", { length: 191 }).notNull(), fromAsset: varchar("fromAsset", { length: 16 }).notNull(), toAsset: varchar("toAsset", { length: 16 }).notNull(), fromAmount: varchar("fromAmount", { length: 64 }).notNull(), toAmount: varchar("toAmount", { length: 64 }).notNull(), rate: varchar("rate", { length: 64 }).notNull(), feeCents: integer("feeCents").default(0).notNull(), status: varchar("status", { length: 24 }).default("completed").notNull(), createdAt: timestamp("createdAt", { withTimezone: true }).defaultNow().notNull() }, table => ({ investorIndex: index("swap_transactions_investor_idx").on(table.investorId) }));

export const swapConfig = pgTable("swapConfig", { id: serial("id").primaryKey(), fromAsset: varchar("fromAsset", { length: 16 }).notNull(), toAsset: varchar("toAsset", { length: 16 }).notNull(), rateMultiplier: varchar("rateMultiplier", { length: 32 }).default("1").notNull(), feeBps: integer("feeBps").default(50).notNull(), active: integer("active").default(1).notNull(), updatedAt: timestamp("updatedAt", { withTimezone: true }).defaultNow().notNull() }, table => ({ pairUnique: uniqueIndex("swap_config_pair_unique").on(table.fromAsset, table.toAsset) }));

export const pushSubscriptions = pgTable("pushSubscriptions", { id: serial("id").primaryKey(), userId: varchar("userId", { length: 191 }).notNull(), endpoint: text("notNull").notNull(), p256dh: text("p256dh").notNull(), auth: text("auth").notNull(), userAgent: varchar("userAgent", { length: 255 }), createdAt: timestamp("createdAt", { withTimezone: true }).defaultNow().notNull() }, table => ({ userIndex: index("push_subscriptions_user_idx").on(table.userId), endpointUnique: uniqueIndex("push_subscriptions_endpoint_unique").on(table.endpoint) }));

export type User = typeof users.$inferSelect;
export type ReferralAttribution = typeof referralAttributions.$inferSelect;
export type ReferralReward = typeof referralRewards.$inferSelect;
export type ReferralWithdrawal = typeof referralWithdrawals.$inferSelect;
export type Notification = typeof notifications.$inferSelect;
export type SwapTransaction = typeof swapTransactions.$inferSelect;
export const schema = { users, accounts, sessions, verificationTokens, deposits, depositInstructions, kycApplications, referralLinks, referralAttributions, referralRewards, referralWithdrawals, investorWithdrawals, plans, investorAccounts, traders, roiEntries, portfolioLedger, portfolioHoldings, copyAllocations, notifications, swapTransactions, swapConfig, pushSubscriptions };
